[build]
  command = "node scripts/setup-env.js && npm ci && npx prisma generate && npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"
  DATABASE_URL = "postgresql://neondb_owner:npg_UxyTKJ5Zw7lH@ep-broad-pond-a2vxuygu-pooler.eu-central-1.aws.neon.tech/neondb?sslmode=require"
  GOOGLE_CLIENT_ID = ""
  GOOGLE_CLIENT_SECRET = ""

# Prevent asset optimization which can break Next.js assets
[build.processing]
  skip_processing = true

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
