[build]
  command = "node scripts/setup-env.js && npm ci && npx prisma generate && npm run build"
  publish = ".next"


[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"
  # Empty credentials to prevent URL errors during build
  GOOGLE_CLIENT_ID = ""
  GOOGLE_CLIENT_SECRET = ""
  # Disable secrets scanning
  SECRETS_SCAN_ENABLED = "false"

# Prevent asset optimization which can break Next.js assets
[build.processing]
  skip_processing = true

# Force trailing slashes
[[redirects]]
  from = "/[path]"
  to = "/[path]/"
  status = 301
  force = false

# Handle Next.js rewrites and redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
